<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>OAC.Backend.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OAC.Backend.csproj" />
    <ProjectReference Include="..\game-adapter\OAC.GameAdapter.csproj" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="8.0.1" />
  </ItemGroup>
</Project>
