#pragma once

/*
 * OAC production-protocol wire types. Keep this header C-compatible and free of
 * process-local pointers: it is shared by the kernel driver and user mode.
 */

#ifdef _KERNEL_MODE
#include <ntddk.h>
#else
#include <Windows.h>
#include <winioctl.h>
#endif

#define OAC_PRODUCTION_PROTOCOL_VERSION 0x00050007UL
#define OAC_V5_VERSION OAC_PRODUCTION_PROTOCOL_VERSION
#define OAC_V5_ULONG_MAX 0xFFFFFFFFUL
#define OAC_V5_MAX_INPUT_SIZE (64UL * 1024UL)
#define OAC_V5_MANIFEST_DIGEST_SIZE 32UL
#define OAC_V5_BACKEND_BINDING_DIGEST_SIZE 32UL
#define OAC_V5_MAX_OUTPUT_SIZE (1024UL * 1024UL)
#define OAC_EVIDENCE_MAX_RECORDS_PER_PAGE 16UL
#define OAC_V5_MAX_EVENT_TEXT 192UL
#define OAC_SNAPSHOT_MAX_RECORDS_PER_PAGE 16UL
#define OAC_SNAPSHOT_MAX_NAME_CHARS 256UL
#define OAC_LAUNCH_MIN_TTL_MS 100UL
#define OAC_LAUNCH_MAX_TTL_MS 10000UL
#define OAC_LAUNCH_MAX_CANONICAL_NT_PATH_CHARS 512UL

#define OAC_V5_IOCTL_ACCESS (FILE_READ_ACCESS | FILE_WRITE_ACCESS)

#define IOCTL_OAC_V5_NEGOTIATE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x810, METHOD_BUFFERED, OAC_V5_IOCTL_ACCESS)
#define IOCTL_OAC_V5_CLAIM_SESSION \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x811, METHOD_BUFFERED, OAC_V5_IOCTL_ACCESS)
#define IOCTL_OAC_V5_SET_CONFIG \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x812, METHOD_BUFFERED, OAC_V5_IOCTL_ACCESS)
#define IOCTL_OAC_V5_RUN_SCAN \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x813, METHOD_BUFFERED, OAC_V5_IOCTL_ACCESS)
#define IOCTL_OAC_READ_EVIDENCE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x814, METHOD_BUFFERED, OAC_V5_IOCTL_ACCESS)
#define IOCTL_OAC_MANAGE_SNAPSHOT \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x815, METHOD_BUFFERED, OAC_V5_IOCTL_ACCESS)
#define IOCTL_OAC_V5_GET_STATUS \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x816, METHOD_BUFFERED, OAC_V5_IOCTL_ACCESS)
#define IOCTL_OAC_V5_REVOKE_SESSION \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x817, METHOD_BUFFERED, OAC_V5_IOCTL_ACCESS)
#define IOCTL_OAC_ARM_LAUNCH \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x818, METHOD_BUFFERED, OAC_V5_IOCTL_ACCESS)
#define IOCTL_OAC_CANCEL_LAUNCH \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x819, METHOD_BUFFERED, OAC_V5_IOCTL_ACCESS)
#define IOCTL_OAC_CONFIRM_TARGET \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x81A, METHOD_BUFFERED, OAC_V5_IOCTL_ACCESS)

typedef ULONGLONG OAC_V5_REQUEST_ID;
typedef ULONGLONG OAC_V5_SCAN_ID;
typedef ULONG OAC_V5_MESSAGE_TYPE;
typedef ULONG OAC_V5_RULE_ID;
typedef ULONG OAC_V5_EVENT_TYPE;
typedef ULONG OAC_V5_OBSERVATION_SEVERITY;
typedef ULONG OAC_V5_POLICY_SEVERITY;
typedef ULONG OAC_V5_CONFIDENCE;
typedef ULONG OAC_V5_CATEGORY;
typedef ULONG OAC_V5_PAYLOAD_TYPE;
typedef ULONG OAC_V5_SESSION_MODE;
typedef ULONG OAC_V5_SESSION_STATE;
typedef ULONG OAC_V5_REASON;
typedef ULONG OAC_V5_REVOKE_REASON;

/* Stable message identities mirror the IOCTL function numbers. */
#define OAC_V5_MESSAGE_NEGOTIATE      0x00000810UL
#define OAC_V5_MESSAGE_CLAIM_SESSION  0x00000811UL
#define OAC_V5_MESSAGE_SET_CONFIG     0x00000812UL
#define OAC_V5_MESSAGE_RUN_SCAN       0x00000813UL
#define OAC_MESSAGE_READ_EVIDENCE     0x00000814UL
#define OAC_MESSAGE_MANAGE_SNAPSHOT   0x00000815UL
#define OAC_V5_MESSAGE_GET_STATUS     0x00000816UL
#define OAC_V5_MESSAGE_REVOKE_SESSION 0x00000817UL
#define OAC_MESSAGE_ARM_LAUNCH     0x00000818UL
#define OAC_MESSAGE_CANCEL_LAUNCH  0x00000819UL
#define OAC_MESSAGE_CONFIRM_TARGET 0x0000081AUL

typedef struct OAC_V5_SESSION_ID_TAG
{
    ULONGLONG High;
    ULONGLONG Low;
} OAC_V5_SESSION_ID, *POAC_V5_SESSION_ID;

typedef struct OAC_LAUNCH_ID_TAG
{
    ULONGLONG High;
    ULONGLONG Low;
} OAC_LAUNCH_ID, *POAC_LAUNCH_ID;

typedef struct OAC_SNAPSHOT_ID_TAG
{
    ULONGLONG High;
    ULONGLONG Low;
} OAC_SNAPSHOT_ID, *POAC_SNAPSHOT_ID;

/* Session modes accepted by OAC_V5_CLAIM_REQUEST.Mode. */
#define OAC_V5_SESSION_PRODUCTION 0x00000001UL
#define OAC_V5_SESSION_DIAGNOSTIC 0x00000002UL

/* Monotonic session states. Unclaimed exists only as device state. */
#define OAC_V5_SESSION_UNCLAIMED      0UL
#define OAC_V5_SESSION_CLAIMED        1UL
#define OAC_V5_SESSION_LAUNCH_PENDING 2UL
#define OAC_V5_SESSION_TARGET_BOUND   3UL
#define OAC_V5_SESSION_MONITORING     4UL
#define OAC_V5_SESSION_REVOKED        5UL
#define OAC_V5_SESSION_CLOSING        6UL

/* Stable reasons returned in OAC_V5_RESPONSE_HEADER.Reason. */
#define OAC_V5_REASON_NONE               0UL
#define OAC_V5_REASON_ALREADY_CLAIMED    1UL
#define OAC_V5_REASON_BUSY               2UL
#define OAC_V5_REASON_WRONG_FILE         3UL
#define OAC_V5_REASON_WRONG_PROCESS      4UL
#define OAC_V5_REASON_STALE_SESSION      5UL
#define OAC_V5_REASON_STALE_GENERATION   6UL
#define OAC_V5_REASON_INVALID_TRANSITION 7UL
#define OAC_V5_REASON_REVOKED            8UL
#define OAC_V5_REASON_CLOSING            9UL
#define OAC_V5_REASON_TARGET_STILL_LIVE  10UL
#define OAC_V5_REASON_UNSUPPORTED_VERSION 11UL
#define OAC_V5_REASON_MALFORMED_REQUEST  12UL

/* Stable revocation provenance returned by GET_STATUS. */
#define OAC_V5_REVOKE_NONE          0UL
#define OAC_V5_REVOKE_REQUESTED     1UL
#define OAC_V5_REVOKE_FILE_CLEANUP  2UL
#define OAC_V5_REVOKE_SERVICE_EXIT  3UL
#define OAC_V5_REVOKE_TARGET_EXIT   4UL
#define OAC_V5_REVOKE_POLICY        5UL
#define OAC_V5_REVOKE_EVIDENCE_LOSS 6UL
#define OAC_V5_REVOKE_DRIVER_STOP   7UL
#define OAC_REVOKE_LAUNCH_CANCELLED 8UL
#define OAC_REVOKE_LAUNCH_EXPIRED   9UL
#define OAC_REVOKE_LAUNCH_MISMATCH  10UL
#define OAC_REVOKE_TARGET_CONFIRMATION_FAILED 11UL

typedef ULONG OAC_LAUNCH_DECISION;
#define OAC_LAUNCH_IGNORE            0UL
#define OAC_LAUNCH_CONSUME_BIND      1UL
#define OAC_LAUNCH_REVOKE_EXPIRED    2UL
#define OAC_LAUNCH_REVOKE_MISMATCH   3UL
#define OAC_LAUNCH_DENY_SERVICE_CREATION_AFTER_BIND 4UL

/* Negotiated driver capabilities. Unsupported capabilities remain clear. */
#define OAC_V5_CAP_SESSION_CONTROL 0x00000001UL
#define OAC_V5_CAP_TYPED_EVENTS    0x00000002UL
#define OAC_V5_CAP_KERNEL_SCAN     0x00000004UL
#define OAC_V5_CAP_PAGED_SNAPSHOTS 0x00000008UL
#define OAC_V5_CAP_DRIVER_GATE     0x00000010UL
#define OAC_V5_CAP_LAUNCH_TICKET   0x00000020UL
#define OAC_V5_CAP_SESSION_LIVENESS 0x00000040UL
#define OAC_V5_CAP_ALL (OAC_V5_CAP_SESSION_CONTROL | \
    OAC_V5_CAP_TYPED_EVENTS | OAC_V5_CAP_KERNEL_SCAN | \
    OAC_V5_CAP_PAGED_SNAPSHOTS | OAC_V5_CAP_DRIVER_GATE | \
    OAC_V5_CAP_LAUNCH_TICKET | OAC_V5_CAP_SESSION_LIVENESS)

#define OAC_V5_PROTOCOL_STRICT_LENGTHS 0x00000001UL
#define OAC_V5_PROTOCOL_TYPED_EVENTS   0x00000002UL
#define OAC_V5_PROTOCOL_V4_DIAGNOSTIC  0x00000004UL
#define OAC_V5_PROTOCOL_FLAGS (OAC_V5_PROTOCOL_STRICT_LENGTHS | \
    OAC_V5_PROTOCOL_TYPED_EVENTS | OAC_V5_PROTOCOL_V4_DIAGNOSTIC)

#define OAC_V5_RESPONSE_MORE_DATA 0x00000001UL
#define OAC_V5_RESPONSE_PARTIAL   0x00000002UL
#define OAC_V5_RESPONSE_REVOKED   0x00000004UL
#define OAC_V5_RESPONSE_FLAGS (OAC_V5_RESPONSE_MORE_DATA | \
    OAC_V5_RESPONSE_PARTIAL | OAC_V5_RESPONSE_REVOKED)

#define OAC_V5_CONFIG_IMAGE_LOG   0x00000001UL
#define OAC_V5_CONFIG_DRIVER_GATE 0x00000002UL
#define OAC_V5_CONFIG_FLAGS (OAC_V5_CONFIG_IMAGE_LOG | \
    OAC_V5_CONFIG_DRIVER_GATE)

/* A production preflight is explicit about which bounded checks completed.
 * The required set is intentionally small and stable; optional diagnostic
 * scans remain on the laboratory interface. */
#define OAC_ENDPOINT_SCAN_KERNEL_MODULES   0x00000001UL
#define OAC_ENDPOINT_SCAN_PROCESS_STATE    0x00000002UL
#define OAC_ENDPOINT_SCAN_DANGEROUS_HANDLES 0x00000004UL
#define OAC_ENDPOINT_SCAN_KERNEL_INTEGRITY 0x00000008UL
#define OAC_ENDPOINT_SCAN_PLATFORM_STATE   0x00000010UL
#define OAC_ENDPOINT_SCAN_FLAGS (OAC_ENDPOINT_SCAN_KERNEL_MODULES | \
    OAC_ENDPOINT_SCAN_PROCESS_STATE | \
    OAC_ENDPOINT_SCAN_DANGEROUS_HANDLES | \
    OAC_ENDPOINT_SCAN_KERNEL_INTEGRITY | \
    OAC_ENDPOINT_SCAN_PLATFORM_STATE)
#define OAC_ENDPOINT_SCAN_REQUIRED_FLAGS OAC_ENDPOINT_SCAN_FLAGS

#define OAC_ENDPOINT_SCAN_COMPLETE   1UL
#define OAC_ENDPOINT_SCAN_INCOMPLETE 2UL

/* Rule namespaces reserve the high 16 bits and keep zero as "no rule". */
#define OAC_V5_RULE_GROUP_MASK    0xFFFF0000UL
#define OAC_V5_RULE_CODE_MASK     0x0000FFFFUL
#define OAC_V5_RULE_SESSION_BASE  0x00010000UL
#define OAC_V5_RULE_PROCESS_BASE  0x00020000UL
#define OAC_V5_RULE_DRIVER_BASE   0x00030000UL
#define OAC_V5_RULE_INTEGRITY_BASE 0x00040000UL
#define OAC_V5_RULE_MEMORY_BASE   0x00050000UL
#define OAC_V5_RULE_DEBUGGER_BASE 0x00060000UL
#define OAC_V5_RULE_OVERLAY_BASE  0x00070000UL
#define OAC_V5_RULE_PLATFORM_BASE 0x00080000UL
#define OAC_V5_RULE_HWID_BASE     0x00090000UL
#define OAC_V5_RULE_POLICY_BASE   0x000A0000UL
#define OAC_V5_RULE_DEVICE_BASE   0x000B0000UL

#define OAC_V5_RULE_SESSION_CLAIMED       0x00010001UL
#define OAC_V5_RULE_SESSION_LOST          0x00010002UL
#define OAC_V5_RULE_SESSION_REVOKED       0x00010003UL
#define OAC_V5_RULE_INVALID_REQUEST       0x00010004UL
#define OAC_V5_RULE_TARGET_BOUND          0x00010005UL
#define OAC_V5_RULE_TARGET_EXITED         0x00010006UL
#define OAC_V5_RULE_PREFLIGHT_STARTED     0x00010007UL
#define OAC_V5_RULE_PREFLIGHT_COMPLETED   0x00010008UL
#define OAC_V5_RULE_PREFLIGHT_INCOMPLETE  0x00010009UL
#define OAC_V5_RULE_HANDLE_RIGHTS_STRIPPED 0x00020001UL
#define OAC_V5_RULE_PROCESS_IMAGE_LOADED    0x00020002UL
#define OAC_V5_RULE_SYSTEM_STATE_PREFLIGHT  0x00020003UL
#define OAC_V5_RULE_SYSTEM_THREAD_PREFLIGHT 0x00020004UL
#define OAC_V5_RULE_DANGEROUS_KERNEL_HANDLE 0x00020005UL
#define OAC_V5_RULE_THREAD_OUTSIDE_IMAGE     0x00020006UL
#define OAC_V5_RULE_TARGET_THREAD_LIFECYCLE  0x00020007UL
#define OAC_V5_RULE_RUNTIME_MODULE_DENIED     0x00020008UL
#define OAC_V5_RULE_THREAD_STACK_ANOMALY      0x00020009UL
#define OAC_V5_RULE_KERNEL_IMAGE_LOADED   0x00030001UL
#define OAC_V5_RULE_DRIVER_DENY_MATCH     0x00030002UL
#define OAC_V5_RULE_DRIVER_GATE_TRIP      0x00030003UL
#define OAC_V5_RULE_DRIVER_PREFLIGHT      0x00030004UL
#define OAC_V5_RULE_DRIVER_HASH_DENIED    0x00030005UL
#define OAC_V5_RULE_DRIVER_TRUST_FAILED   0x00030006UL
#define OAC_V5_RULE_DRIVER_REVIEW_REQUIRED 0x00030007UL
#define OAC_V5_RULE_DRIVER_FAMILY_DENIED  0x00030008UL
#define OAC_V5_RULE_KERNEL_INTEGRITY      0x00040001UL
#define OAC_V5_RULE_CPU_STATE             0x00040002UL
#define OAC_V5_RULE_EXECUTABLE_NONIMAGE_MEMORY 0x00050001UL
#define OAC_V5_RULE_WRITABLE_EXECUTABLE_MEMORY 0x00050002UL
#define OAC_V5_RULE_UNBACKED_PE_IMAGE      0x00050003UL
#define OAC_V5_RULE_DIRECT_SYSCALL_STUB    0x00050004UL
#define OAC_V5_RULE_DEBUGGER_PREFLIGHT    0x00060001UL
#define OAC_V5_RULE_THREAD_DEBUG_REGISTERS 0x00060002UL
#define OAC_V5_RULE_INSTRUMENTATION_CALLBACK 0x00060003UL
#define OAC_V5_RULE_VIRTUALIZATION        0x00080001UL
#define OAC_V5_RULE_PLATFORM_PREFLIGHT    0x00080002UL

#define OAC_V5_EVENT_OBSERVATION            1UL
#define OAC_V5_EVENT_POLICY_VIOLATION       2UL
#define OAC_V5_EVENT_CAPABILITY_CHANGE      3UL
#define OAC_V5_EVENT_SCAN_STARTED           4UL
#define OAC_V5_EVENT_SCAN_COMPLETED         5UL
#define OAC_V5_EVENT_SCAN_INCOMPLETE        6UL
#define OAC_V5_EVENT_SESSION_STATE_CHANGED  7UL
#define OAC_V5_EVENT_EVIDENCE_LOSS          8UL
#define OAC_V5_EVENT_REVOCATION             9UL

#define OAC_V5_OBSERVATION_INFO     0UL
#define OAC_V5_OBSERVATION_LOW      1UL
#define OAC_V5_OBSERVATION_MEDIUM   2UL
#define OAC_V5_OBSERVATION_HIGH     3UL
#define OAC_V5_OBSERVATION_CRITICAL 4UL

#define OAC_V5_POLICY_NOT_EVALUATED 0UL
#define OAC_V5_POLICY_INFO          1UL
#define OAC_V5_POLICY_LOW           2UL
#define OAC_V5_POLICY_MEDIUM        3UL
#define OAC_V5_POLICY_HIGH          4UL
#define OAC_V5_POLICY_CRITICAL      5UL

#define OAC_V5_CONFIDENCE_UNKNOWN 0UL
#define OAC_V5_CONFIDENCE_LOW     1UL
#define OAC_V5_CONFIDENCE_MEDIUM  2UL
#define OAC_V5_CONFIDENCE_HIGH    3UL

#define OAC_V5_EVIDENCE_KERNEL_SOURCE     0x0000000000000001ULL
#define OAC_V5_EVIDENCE_CALLBACK_SOURCE   0x0000000000000002ULL
#define OAC_V5_EVIDENCE_CROSS_VIEW        0x0000000000000004ULL
#define OAC_V5_EVIDENCE_SIGNATURE_CHECKED 0x0000000000000008ULL
#define OAC_V5_EVIDENCE_EXACT_PROFILE     0x0000000000000010ULL
#define OAC_V5_EVIDENCE_TRUNCATED         0x0000000000000020ULL
#define OAC_V5_EVIDENCE_INCOMPLETE        0x0000000000000040ULL
#define OAC_V5_EVIDENCE_SERVICE_SOURCE    0x0000000000000080ULL
#define OAC_V5_EVIDENCE_FLAGS             0x00000000000000FFULL

#define OAC_V5_PAYLOAD_NONE   0UL
#define OAC_V5_PAYLOAD_BINARY 1UL
#define OAC_V5_PAYLOAD_UTF16  2UL

/* No event-record flags are defined in the production protocol. */
#define OAC_V5_EVENT_FLAGS 0UL

#define OAC_V5_CATEGORY_GENERAL        0UL
#define OAC_V5_CATEGORY_PROCESS        1UL
#define OAC_V5_CATEGORY_HANDLE         2UL
#define OAC_V5_CATEGORY_MODULE         3UL
#define OAC_V5_CATEGORY_DRIVER         4UL
#define OAC_V5_CATEGORY_MEMORY         5UL
#define OAC_V5_CATEGORY_THREAD         6UL
#define OAC_V5_CATEGORY_DEBUGGER       7UL
#define OAC_V5_CATEGORY_INTEGRITY      8UL
#define OAC_V5_CATEGORY_VIRTUALIZATION 9UL
#define OAC_V5_CATEGORY_SERVICE        10UL
#define OAC_V5_CATEGORY_DEVICE         11UL
#define OAC_V5_CATEGORY_WINDOW         12UL
#define OAC_V5_CATEGORY_HWID           13UL

#define OAC_EVIDENCE_CHANNEL_ALERT 1UL
#define OAC_EVIDENCE_CHANNEL_EVENT 2UL

#define OAC_SNAPSHOT_OPERATION_OPEN  1UL
#define OAC_SNAPSHOT_OPERATION_READ  2UL
#define OAC_SNAPSHOT_OPERATION_CLOSE 3UL

#define OAC_SNAPSHOT_TYPE_KERNEL_MODULES 1UL

#define OAC_SNAPSHOT_STATE_READY  1UL
#define OAC_SNAPSHOT_STATE_FAILED 2UL
#define OAC_SNAPSHOT_STATE_CLOSED 3UL

#define OAC_SNAPSHOT_RECORD_KERNEL_MODULE 1UL
#define OAC_SNAPSHOT_RECORD_FLAGS 0UL

typedef struct OAC_V5_REQUEST_HEADER_TAG
{
    ULONG Version;
    ULONG Size;
    OAC_V5_REQUEST_ID RequestId;
    OAC_V5_SESSION_ID SessionId;
    ULONGLONG Generation;
    ULONG Flags;
    OAC_V5_MESSAGE_TYPE MessageType;
} OAC_V5_REQUEST_HEADER, *POAC_V5_REQUEST_HEADER;

typedef struct OAC_V5_RESPONSE_HEADER_TAG
{
    ULONG Version;
    ULONG Size;
    OAC_V5_REQUEST_ID RequestId;
    OAC_V5_SESSION_ID SessionId;
    ULONGLONG Generation;
    LONG Status;
    OAC_V5_REASON Reason;
    ULONG Flags;
    OAC_V5_MESSAGE_TYPE MessageType;
} OAC_V5_RESPONSE_HEADER, *POAC_V5_RESPONSE_HEADER;

typedef struct OAC_V5_NEGOTIATE_REQUEST_TAG
{
    OAC_V5_REQUEST_HEADER Header;
    ULONG MinimumVersion;
    ULONG MaximumVersion;
} OAC_V5_NEGOTIATE_REQUEST, *POAC_V5_NEGOTIATE_REQUEST;

typedef struct OAC_V5_NEGOTIATE_RESPONSE_TAG
{
    OAC_V5_RESPONSE_HEADER Header;
    ULONG MinimumVersion;
    ULONG SelectedVersion;
    ULONG MaximumVersion;
    ULONG Capabilities;
    ULONG MaximumInputSize;
    ULONG MaximumOutputSize;
    ULONG MaximumEventCount;
    ULONG ProtocolFlags;
} OAC_V5_NEGOTIATE_RESPONSE, *POAC_V5_NEGOTIATE_RESPONSE;

typedef struct OAC_V5_CLAIM_REQUEST_TAG
{
    OAC_V5_REQUEST_HEADER Header;
    OAC_V5_SESSION_MODE Mode;
    ULONG Reserved;
    UCHAR BackendBindingSha256[OAC_V5_BACKEND_BINDING_DIGEST_SIZE];
} OAC_V5_CLAIM_REQUEST, *POAC_V5_CLAIM_REQUEST;

typedef struct OAC_V5_CLAIM_RESPONSE_TAG
{
    OAC_V5_RESPONSE_HEADER Header;
    OAC_V5_SESSION_STATE State;
    ULONG Capabilities;
} OAC_V5_CLAIM_RESPONSE, *POAC_V5_CLAIM_RESPONSE;

typedef struct OAC_ENDPOINT_CONFIG_REQUEST_TAG
{
    OAC_V5_REQUEST_HEADER Header;
    ULONG ConfigurationFlags;
    ULONG Reserved;
} OAC_ENDPOINT_CONFIG_REQUEST, *POAC_ENDPOINT_CONFIG_REQUEST;

typedef struct OAC_ENDPOINT_CONFIG_RESPONSE_TAG
{
    OAC_V5_RESPONSE_HEADER Header;
    OAC_V5_SESSION_STATE State;
    ULONG ConfigurationFlags;
} OAC_ENDPOINT_CONFIG_RESPONSE, *POAC_ENDPOINT_CONFIG_RESPONSE;

typedef struct OAC_ENDPOINT_SCAN_REQUEST_TAG
{
    OAC_V5_REQUEST_HEADER Header;
    ULONG RequestedFlags;
    ULONG Reserved;
} OAC_ENDPOINT_SCAN_REQUEST, *POAC_ENDPOINT_SCAN_REQUEST;

typedef struct OAC_ENDPOINT_SCAN_RESPONSE_TAG
{
    OAC_V5_RESPONSE_HEADER Header;
    OAC_V5_SCAN_ID ScanId;
    ULONGLONG StartedTimestamp100ns;
    ULONGLONG CompletedTimestamp100ns;
    ULONG RequestedFlags;
    ULONG CompletedFlags;
    ULONG EvidenceRecordCount;
    ULONG State;
    LONG FailureStatus;
    ULONG Reserved;
} OAC_ENDPOINT_SCAN_RESPONSE, *POAC_ENDPOINT_SCAN_RESPONSE;

typedef struct OAC_V5_STATUS_REQUEST_TAG
{
    OAC_V5_REQUEST_HEADER Header;
} OAC_V5_STATUS_REQUEST, *POAC_V5_STATUS_REQUEST;

typedef struct OAC_V5_STATUS_RESPONSE_TAG
{
    OAC_V5_RESPONSE_HEADER Header;
    OAC_V5_SESSION_STATE State;
    ULONG Capabilities;
    ULONG ConfigurationFlags;
    OAC_V5_REVOKE_REASON RevokeReason;
    ULONGLONG ServiceProcessId;
    ULONGLONG TargetProcessId;
    ULONGLONG EventsWritten;
    ULONGLONG EventsDropped;
    ULONGLONG PostStartLoads;
    ULONGLONG DriverGateTrips;
    ULONGLONG SessionLossSequence;
    OAC_V5_REVOKE_REASON LastSessionLossReason;
    OAC_V5_SESSION_MODE SessionMode;
    OAC_V5_SCAN_ID LastCompletedScanId;
    UCHAR ManifestSha256[OAC_V5_MANIFEST_DIGEST_SIZE];
    UCHAR BackendBindingSha256[OAC_V5_BACKEND_BINDING_DIGEST_SIZE];
} OAC_V5_STATUS_RESPONSE, *POAC_V5_STATUS_RESPONSE;

typedef struct OAC_REVOKE_SESSION_REQUEST_TAG
{
    OAC_V5_REQUEST_HEADER Header;
    OAC_V5_REVOKE_REASON RevokeReason;
    ULONG Reserved;
} OAC_REVOKE_SESSION_REQUEST, *POAC_REVOKE_SESSION_REQUEST;

typedef struct OAC_REVOKE_SESSION_RESPONSE_TAG
{
    OAC_V5_RESPONSE_HEADER Header;
    OAC_V5_SESSION_STATE State;
    OAC_V5_REVOKE_REASON RevokeReason;
    ULONGLONG SessionLossSequence;
    OAC_V5_REVOKE_REASON LastSessionLossReason;
    ULONG Reserved;
} OAC_REVOKE_SESSION_RESPONSE, *POAC_REVOKE_SESSION_RESPONSE;

/* Path lengths count WCHARs and exclude the null terminator. The service
 * resolves both names from one locked executable handle. CanonicalNtPath uses
 * the volume-device form (\Device\...), while CanonicalDosDevicePath uses the
 * DOS-device form (\??\C:\...). Unused path storage, including each
 * terminator, must be zero. */
typedef struct OAC_ARM_LAUNCH_REQUEST_TAG
{
    OAC_V5_REQUEST_HEADER Header;
    ULONG TimeToLiveMilliseconds;
    ULONG CanonicalNtPathLength;
    ULONG CanonicalDosDevicePathLength;
    ULONG Reserved;
    UCHAR ManifestSha256[OAC_V5_MANIFEST_DIGEST_SIZE];
    WCHAR CanonicalNtPath[OAC_LAUNCH_MAX_CANONICAL_NT_PATH_CHARS];
    WCHAR CanonicalDosDevicePath[OAC_LAUNCH_MAX_CANONICAL_NT_PATH_CHARS];
} OAC_ARM_LAUNCH_REQUEST, *POAC_ARM_LAUNCH_REQUEST;

typedef struct OAC_ARM_LAUNCH_RESPONSE_TAG
{
    OAC_V5_RESPONSE_HEADER Header;
    OAC_LAUNCH_ID LaunchId;
    /* Absolute KeQueryInterruptTime-compatible expiration value. */
    ULONGLONG ExpirationInterruptTime100ns;
    OAC_V5_SESSION_STATE State;
    ULONG Reserved;
} OAC_ARM_LAUNCH_RESPONSE, *POAC_ARM_LAUNCH_RESPONSE;

typedef struct OAC_CANCEL_LAUNCH_REQUEST_TAG
{
    OAC_V5_REQUEST_HEADER Header;
    OAC_LAUNCH_ID LaunchId;
} OAC_CANCEL_LAUNCH_REQUEST, *POAC_CANCEL_LAUNCH_REQUEST;

typedef struct OAC_CANCEL_LAUNCH_RESPONSE_TAG
{
    OAC_V5_RESPONSE_HEADER Header;
    OAC_V5_SESSION_STATE State;
    ULONG Reserved;
} OAC_CANCEL_LAUNCH_RESPONSE, *POAC_CANCEL_LAUNCH_RESPONSE;

typedef struct OAC_CONFIRM_TARGET_REQUEST_TAG
{
    OAC_V5_REQUEST_HEADER Header;
    OAC_LAUNCH_ID LaunchId;
    ULONGLONG TargetProcessHandle;
} OAC_CONFIRM_TARGET_REQUEST, *POAC_CONFIRM_TARGET_REQUEST;

typedef struct OAC_CONFIRM_TARGET_RESPONSE_TAG
{
    OAC_V5_RESPONSE_HEADER Header;
    ULONGLONG TargetProcessId;
    OAC_V5_SESSION_STATE State;
    ULONG Reserved;
} OAC_CONFIRM_TARGET_RESPONSE, *POAC_CONFIRM_TARGET_RESPONSE;

typedef struct OAC_EVIDENCE_READ_REQUEST_TAG
{
    OAC_V5_REQUEST_HEADER Header;
    ULONG Channel;
    ULONG MaximumRecords;
    ULONGLONG AfterSequence;
    ULONGLONG AcknowledgeThrough;
    ULONGLONG Reserved;
} OAC_EVIDENCE_READ_REQUEST, *POAC_EVIDENCE_READ_REQUEST;

/* Display text is optional and has no policy meaning. PayloadLength is bytes
 * used in Text; UTF-16 payloads include their trailing null WCHAR. */
typedef struct OAC_V5_EVENT_RECORD_TAG
{
    ULONG Version;
    ULONG Size;
    OAC_V5_RULE_ID RuleId;
    OAC_V5_EVENT_TYPE EventType;
    OAC_V5_OBSERVATION_SEVERITY ObservationSeverity;
    OAC_V5_POLICY_SEVERITY PolicySeverity;
    OAC_V5_CONFIDENCE Confidence;
    OAC_V5_CATEGORY Category;
    OAC_V5_PAYLOAD_TYPE PayloadType;
    ULONG Reserved;
    OAC_V5_SESSION_ID SessionId;
    ULONGLONG Generation;
    ULONGLONG Sequence;
    ULONGLONG Timestamp100ns;
    OAC_V5_SCAN_ID ScanId;
    ULONGLONG IngestionTimestamp100ns;
    ULONGLONG ServiceSequence;
    ULONGLONG OccurrenceCount;
    ULONGLONG FirstOccurrence100ns;
    ULONGLONG LastOccurrence100ns;
    ULONGLONG ProcessId;
    ULONGLONG ThreadId;
    ULONGLONG Address;
    ULONGLONG Auxiliary;
    ULONGLONG EvidenceFlags;
    ULONG PayloadLength;
    ULONG Flags;
    WCHAR Text[OAC_V5_MAX_EVENT_TEXT];
} OAC_V5_EVENT_RECORD, *POAC_V5_EVENT_RECORD;

typedef struct OAC_EVIDENCE_READ_RESPONSE_TAG
{
    OAC_V5_RESPONSE_HEADER Header;
    ULONG Channel;
    ULONG RecordCount;
    ULONGLONG PublishedSequence;
    ULONGLONG FirstAvailableSequence;
    ULONGLONG LastAvailableSequence;
    ULONGLONG AcknowledgedSequence;
    ULONGLONG DroppedCount;
    ULONGLONG FirstLostSequence;
    ULONGLONG LostHighCount;
    ULONGLONG LostCriticalCount;
    ULONG LossLatched;
    ULONG Reserved;
    OAC_V5_EVENT_RECORD Records[ANYSIZE_ARRAY];
} OAC_EVIDENCE_READ_RESPONSE, *POAC_EVIDENCE_READ_RESPONSE;

typedef struct OAC_SNAPSHOT_RECORD_TAG
{
    ULONG Version;
    ULONG Size;
    ULONG RecordType;
    ULONG Flags;
    ULONGLONG Index;
    ULONGLONG Address;
    ULONGLONG Length;
    ULONG NameLength;
    ULONG Reserved;
    WCHAR Name[OAC_SNAPSHOT_MAX_NAME_CHARS];
} OAC_SNAPSHOT_RECORD, *POAC_SNAPSHOT_RECORD;

typedef struct OAC_SNAPSHOT_REQUEST_TAG
{
    OAC_V5_REQUEST_HEADER Header;
    ULONG Operation;
    ULONG SnapshotType;
    OAC_SNAPSHOT_ID SnapshotId;
    ULONGLONG CursorGeneration;
    ULONGLONG Cursor;
    ULONG MaximumRecords;
    ULONG Reserved;
} OAC_SNAPSHOT_REQUEST, *POAC_SNAPSHOT_REQUEST;

typedef struct OAC_SNAPSHOT_RESPONSE_TAG
{
    OAC_V5_RESPONSE_HEADER Header;
    OAC_SNAPSHOT_ID SnapshotId;
    OAC_V5_SCAN_ID ScanId;
    ULONGLONG CreatedTimestamp100ns;
    ULONGLONG ExpirationInterruptTime100ns;
    ULONGLONG CursorGeneration;
    ULONGLONG Cursor;
    ULONGLONG NextCursor;
    ULONG SnapshotType;
    ULONG State;
    ULONG TotalItems;
    ULONG AvailableItems;
    ULONG RecordCount;
    ULONG Truncated;
    LONG FailureStatus;
    ULONG Reserved;
    OAC_SNAPSHOT_RECORD Records[ANYSIZE_ARRAY];
} OAC_SNAPSHOT_RESPONSE, *POAC_SNAPSHOT_RESPONSE;

#ifdef __cplusplus
#define OAC_V5_STATIC_ASSERT(Expression, Message) static_assert((Expression), Message)
#elif defined(_KERNEL_MODE)
#define OAC_V5_STATIC_ASSERT(Expression, Message) C_ASSERT(Expression)
#else
#define OAC_V5_STATIC_ASSERT(Expression, Message) _Static_assert((Expression), Message)
#endif

OAC_V5_STATIC_ASSERT(sizeof(WCHAR) == 2, "OAC v5 requires 16-bit WCHAR");
OAC_V5_STATIC_ASSERT(((IOCTL_OAC_V5_NEGOTIATE >> 2) & 0xFFFUL) ==
    OAC_V5_MESSAGE_NEGOTIATE, "negotiate message ID drifted");
OAC_V5_STATIC_ASSERT(((IOCTL_OAC_V5_CLAIM_SESSION >> 2) & 0xFFFUL) ==
    OAC_V5_MESSAGE_CLAIM_SESSION, "claim message ID drifted");
OAC_V5_STATIC_ASSERT(((IOCTL_OAC_V5_SET_CONFIG >> 2) & 0xFFFUL) ==
    OAC_V5_MESSAGE_SET_CONFIG, "config message ID drifted");
OAC_V5_STATIC_ASSERT(((IOCTL_OAC_V5_RUN_SCAN >> 2) & 0xFFFUL) ==
    OAC_V5_MESSAGE_RUN_SCAN, "scan message ID drifted");
OAC_V5_STATIC_ASSERT(((IOCTL_OAC_READ_EVIDENCE >> 2) & 0xFFFUL) ==
    OAC_MESSAGE_READ_EVIDENCE, "evidence message ID drifted");
OAC_V5_STATIC_ASSERT(((IOCTL_OAC_MANAGE_SNAPSHOT >> 2) & 0xFFFUL) ==
    OAC_MESSAGE_MANAGE_SNAPSHOT, "snapshot message ID drifted");
OAC_V5_STATIC_ASSERT(((IOCTL_OAC_V5_GET_STATUS >> 2) & 0xFFFUL) ==
    OAC_V5_MESSAGE_GET_STATUS, "status message ID drifted");
OAC_V5_STATIC_ASSERT(((IOCTL_OAC_V5_REVOKE_SESSION >> 2) & 0xFFFUL) ==
    OAC_V5_MESSAGE_REVOKE_SESSION, "revoke message ID drifted");
OAC_V5_STATIC_ASSERT(((IOCTL_OAC_ARM_LAUNCH >> 2) & 0xFFFUL) ==
    OAC_MESSAGE_ARM_LAUNCH, "arm-launch message ID drifted");
OAC_V5_STATIC_ASSERT(((IOCTL_OAC_CANCEL_LAUNCH >> 2) & 0xFFFUL) ==
    OAC_MESSAGE_CANCEL_LAUNCH, "cancel-launch message ID drifted");
OAC_V5_STATIC_ASSERT(((IOCTL_OAC_CONFIRM_TARGET >> 2) & 0xFFFUL) ==
    OAC_MESSAGE_CONFIRM_TARGET, "confirm-target message ID drifted");
OAC_V5_STATIC_ASSERT(sizeof(OAC_V5_SESSION_ID) == 16,
    "OAC_V5_SESSION_ID layout changed");
OAC_V5_STATIC_ASSERT(sizeof(OAC_LAUNCH_ID) == 16,
    "OAC_LAUNCH_ID layout changed");
OAC_V5_STATIC_ASSERT(sizeof(OAC_SNAPSHOT_ID) == 16,
    "OAC_SNAPSHOT_ID layout changed");
OAC_V5_STATIC_ASSERT(sizeof(OAC_V5_REQUEST_HEADER) == 48,
    "OAC_V5_REQUEST_HEADER layout changed");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_REQUEST_HEADER, RequestId) == 8,
    "OAC_V5_REQUEST_HEADER request ID moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_REQUEST_HEADER, SessionId) == 16,
    "OAC_V5_REQUEST_HEADER session ID moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_REQUEST_HEADER, Generation) == 32,
    "OAC_V5_REQUEST_HEADER generation moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_REQUEST_HEADER, Flags) == 40,
    "OAC_V5_REQUEST_HEADER flags moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_REQUEST_HEADER, MessageType) == 44,
    "OAC_V5_REQUEST_HEADER message type moved");
OAC_V5_STATIC_ASSERT(sizeof(OAC_V5_RESPONSE_HEADER) == 56,
    "OAC_V5_RESPONSE_HEADER layout changed");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_RESPONSE_HEADER, RequestId) == 8,
    "OAC_V5_RESPONSE_HEADER request ID moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_RESPONSE_HEADER, SessionId) == 16,
    "OAC_V5_RESPONSE_HEADER session ID moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_RESPONSE_HEADER, Generation) == 32,
    "OAC_V5_RESPONSE_HEADER generation moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_RESPONSE_HEADER, Status) == 40,
    "OAC_V5_RESPONSE_HEADER status moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_RESPONSE_HEADER, Flags) == 48,
    "OAC_V5_RESPONSE_HEADER flags moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_RESPONSE_HEADER, MessageType) == 52,
    "OAC_V5_RESPONSE_HEADER message type moved");
OAC_V5_STATIC_ASSERT(sizeof(OAC_V5_NEGOTIATE_REQUEST) == 56,
    "OAC_V5_NEGOTIATE_REQUEST layout changed");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_NEGOTIATE_REQUEST, MinimumVersion) == 48,
    "OAC_V5_NEGOTIATE_REQUEST payload moved");
OAC_V5_STATIC_ASSERT(sizeof(OAC_V5_NEGOTIATE_RESPONSE) == 88,
    "OAC_V5_NEGOTIATE_RESPONSE layout changed");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_NEGOTIATE_RESPONSE, MinimumVersion) == 56,
    "OAC_V5_NEGOTIATE_RESPONSE payload moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_NEGOTIATE_RESPONSE, MaximumInputSize) == 72,
    "OAC_V5_NEGOTIATE_RESPONSE limits moved");
OAC_V5_STATIC_ASSERT(sizeof(OAC_V5_CLAIM_REQUEST) == 88,
    "OAC_V5_CLAIM_REQUEST layout changed");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_CLAIM_REQUEST, Mode) == 48,
    "OAC_V5_CLAIM_REQUEST payload moved");
OAC_V5_STATIC_ASSERT(
    FIELD_OFFSET(OAC_V5_CLAIM_REQUEST, BackendBindingSha256) == 56,
    "OAC_V5_CLAIM_REQUEST backend binding moved");
OAC_V5_STATIC_ASSERT(sizeof(OAC_V5_CLAIM_RESPONSE) == 64,
    "OAC_V5_CLAIM_RESPONSE layout changed");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_CLAIM_RESPONSE, State) == 56,
    "OAC_V5_CLAIM_RESPONSE payload moved");
OAC_V5_STATIC_ASSERT(sizeof(OAC_ENDPOINT_CONFIG_REQUEST) == 56,
    "OAC_ENDPOINT_CONFIG_REQUEST layout changed");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ENDPOINT_CONFIG_REQUEST,
    ConfigurationFlags) == 48, "endpoint configuration flags moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ENDPOINT_CONFIG_REQUEST,
    Reserved) == 52, "endpoint configuration reserved field moved");
OAC_V5_STATIC_ASSERT(sizeof(OAC_ENDPOINT_CONFIG_RESPONSE) == 64,
    "OAC_ENDPOINT_CONFIG_RESPONSE layout changed");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ENDPOINT_CONFIG_RESPONSE,
    State) == 56, "endpoint configuration state moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ENDPOINT_CONFIG_RESPONSE,
    ConfigurationFlags) == 60, "endpoint configuration response moved");
OAC_V5_STATIC_ASSERT(sizeof(OAC_ENDPOINT_SCAN_REQUEST) == 56,
    "OAC_ENDPOINT_SCAN_REQUEST layout changed");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ENDPOINT_SCAN_REQUEST,
    RequestedFlags) == 48, "endpoint scan flags moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ENDPOINT_SCAN_REQUEST,
    Reserved) == 52, "endpoint scan reserved field moved");
OAC_V5_STATIC_ASSERT(sizeof(OAC_ENDPOINT_SCAN_RESPONSE) == 104,
    "OAC_ENDPOINT_SCAN_RESPONSE layout changed");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ENDPOINT_SCAN_RESPONSE,
    ScanId) == 56, "endpoint scan ID moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ENDPOINT_SCAN_RESPONSE,
    StartedTimestamp100ns) == 64, "endpoint scan start time moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ENDPOINT_SCAN_RESPONSE,
    CompletedTimestamp100ns) == 72, "endpoint scan completion time moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ENDPOINT_SCAN_RESPONSE,
    RequestedFlags) == 80, "endpoint requested flags moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ENDPOINT_SCAN_RESPONSE,
    CompletedFlags) == 84, "endpoint completed flags moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ENDPOINT_SCAN_RESPONSE,
    EvidenceRecordCount) == 88, "endpoint evidence count moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ENDPOINT_SCAN_RESPONSE,
    State) == 92, "endpoint scan state moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ENDPOINT_SCAN_RESPONSE,
    FailureStatus) == 96, "endpoint scan failure status moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ENDPOINT_SCAN_RESPONSE,
    Reserved) == 100, "endpoint scan reserved field moved");
OAC_V5_STATIC_ASSERT(sizeof(OAC_V5_STATUS_REQUEST) == 48,
    "OAC_V5_STATUS_REQUEST layout changed");
OAC_V5_STATIC_ASSERT(sizeof(OAC_V5_STATUS_RESPONSE) == 208,
    "OAC_V5_STATUS_RESPONSE layout changed");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_STATUS_RESPONSE, State) == 56,
    "OAC_V5_STATUS_RESPONSE state moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_STATUS_RESPONSE, ServiceProcessId) == 72,
    "OAC_V5_STATUS_RESPONSE identities moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_STATUS_RESPONSE, DriverGateTrips) == 112,
    "OAC_V5_STATUS_RESPONSE counters moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_STATUS_RESPONSE, SessionLossSequence) == 120,
    "OAC_V5_STATUS_RESPONSE liveness sequence moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_STATUS_RESPONSE, LastSessionLossReason) == 128,
    "OAC_V5_STATUS_RESPONSE liveness reason moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_STATUS_RESPONSE, SessionMode) == 132,
    "OAC_V5_STATUS_RESPONSE session mode moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_STATUS_RESPONSE,
    LastCompletedScanId) == 136,
    "OAC_V5_STATUS_RESPONSE preflight identity moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_STATUS_RESPONSE, ManifestSha256) == 144,
    "OAC_V5_STATUS_RESPONSE manifest digest moved");
OAC_V5_STATIC_ASSERT(
    FIELD_OFFSET(OAC_V5_STATUS_RESPONSE, BackendBindingSha256) == 176,
    "OAC_V5_STATUS_RESPONSE backend binding moved");
OAC_V5_STATIC_ASSERT(sizeof(OAC_REVOKE_SESSION_REQUEST) == 56,
    "OAC_REVOKE_SESSION_REQUEST layout changed");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_REVOKE_SESSION_REQUEST, RevokeReason) == 48,
    "OAC_REVOKE_SESSION_REQUEST reason moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_REVOKE_SESSION_REQUEST, Reserved) == 52,
    "OAC_REVOKE_SESSION_REQUEST reserved field moved");
OAC_V5_STATIC_ASSERT(sizeof(OAC_REVOKE_SESSION_RESPONSE) == 80,
    "OAC_REVOKE_SESSION_RESPONSE layout changed");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_REVOKE_SESSION_RESPONSE, State) == 56,
    "OAC_REVOKE_SESSION_RESPONSE state moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_REVOKE_SESSION_RESPONSE, RevokeReason) == 60,
    "OAC_REVOKE_SESSION_RESPONSE reason moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_REVOKE_SESSION_RESPONSE, SessionLossSequence) == 64,
    "OAC_REVOKE_SESSION_RESPONSE liveness sequence moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_REVOKE_SESSION_RESPONSE, LastSessionLossReason) == 72,
    "OAC_REVOKE_SESSION_RESPONSE liveness reason moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_REVOKE_SESSION_RESPONSE, Reserved) == 76,
    "OAC_REVOKE_SESSION_RESPONSE reserved field moved");
OAC_V5_STATIC_ASSERT(sizeof(OAC_ARM_LAUNCH_REQUEST) == 2144,
    "OAC_ARM_LAUNCH_REQUEST layout changed");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ARM_LAUNCH_REQUEST,
    TimeToLiveMilliseconds) == 48, "arm-launch TTL moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ARM_LAUNCH_REQUEST,
    CanonicalNtPathLength) == 52, "arm-launch path length moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ARM_LAUNCH_REQUEST,
    CanonicalDosDevicePathLength) == 56,
    "arm-launch DOS-device path length moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ARM_LAUNCH_REQUEST,
    Reserved) == 60, "arm-launch reserved field moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ARM_LAUNCH_REQUEST,
    ManifestSha256) == 64, "arm-launch manifest digest moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ARM_LAUNCH_REQUEST,
    CanonicalNtPath) == 96, "arm-launch path moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ARM_LAUNCH_REQUEST,
    CanonicalDosDevicePath) == 1120,
    "arm-launch DOS-device path moved");
OAC_V5_STATIC_ASSERT(sizeof(OAC_ARM_LAUNCH_RESPONSE) == 88,
    "OAC_ARM_LAUNCH_RESPONSE layout changed");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ARM_LAUNCH_RESPONSE,
    LaunchId) == 56, "arm-launch ID moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ARM_LAUNCH_RESPONSE,
    ExpirationInterruptTime100ns) == 72,
    "arm-launch expiration moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ARM_LAUNCH_RESPONSE,
    State) == 80, "arm-launch state moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_ARM_LAUNCH_RESPONSE,
    Reserved) == 84, "arm-launch reserved field moved");
OAC_V5_STATIC_ASSERT(sizeof(OAC_CANCEL_LAUNCH_REQUEST) == 64,
    "OAC_CANCEL_LAUNCH_REQUEST layout changed");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_CANCEL_LAUNCH_REQUEST,
    LaunchId) == 48, "cancel-launch ID moved");
OAC_V5_STATIC_ASSERT(sizeof(OAC_CANCEL_LAUNCH_RESPONSE) == 64,
    "OAC_CANCEL_LAUNCH_RESPONSE layout changed");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_CANCEL_LAUNCH_RESPONSE,
    State) == 56, "cancel-launch state moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_CANCEL_LAUNCH_RESPONSE,
    Reserved) == 60, "cancel-launch reserved field moved");
OAC_V5_STATIC_ASSERT(sizeof(OAC_CONFIRM_TARGET_REQUEST) == 72,
    "OAC_CONFIRM_TARGET_REQUEST layout changed");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_CONFIRM_TARGET_REQUEST,
    LaunchId) == 48, "confirm-target ID moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_CONFIRM_TARGET_REQUEST,
    TargetProcessHandle) == 64, "confirm-target handle moved");
OAC_V5_STATIC_ASSERT(sizeof(OAC_CONFIRM_TARGET_RESPONSE) == 72,
    "OAC_CONFIRM_TARGET_RESPONSE layout changed");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_CONFIRM_TARGET_RESPONSE,
    TargetProcessId) == 56, "confirm-target PID moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_CONFIRM_TARGET_RESPONSE,
    State) == 64, "confirm-target state moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_CONFIRM_TARGET_RESPONSE,
    Reserved) == 68, "confirm-target reserved field moved");
OAC_V5_STATIC_ASSERT(sizeof(OAC_EVIDENCE_READ_REQUEST) == 80,
    "OAC_EVIDENCE_READ_REQUEST layout changed");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_EVIDENCE_READ_REQUEST,
    Header) == 0, "evidence request header moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_EVIDENCE_READ_REQUEST,
    Channel) == 48, "evidence channel moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_EVIDENCE_READ_REQUEST,
    MaximumRecords) == 52, "evidence page bound moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_EVIDENCE_READ_REQUEST,
    AfterSequence) == 56, "evidence cursor moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_EVIDENCE_READ_REQUEST,
    AcknowledgeThrough) == 64, "evidence acknowledgement moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_EVIDENCE_READ_REQUEST,
    Reserved) == 72, "evidence reserved field moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD, Version) == 0,
    "OAC_V5_EVENT_RECORD version moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD, Size) == 4,
    "OAC_V5_EVENT_RECORD size moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD, RuleId) == 8,
    "OAC_V5_EVENT_RECORD rule ID moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD, EventType) == 12,
    "OAC_V5_EVENT_RECORD event type moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD,
    ObservationSeverity) == 16,
    "OAC_V5_EVENT_RECORD observation severity moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD, PolicySeverity) == 20,
    "OAC_V5_EVENT_RECORD policy severity moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD, Confidence) == 24,
    "OAC_V5_EVENT_RECORD confidence moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD, Category) == 28,
    "OAC_V5_EVENT_RECORD category moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD, PayloadType) == 32,
    "OAC_V5_EVENT_RECORD payload type moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD, Reserved) == 36,
    "OAC_V5_EVENT_RECORD reserved field moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD, SessionId) == 40,
    "OAC_V5_EVENT_RECORD session ID moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD, Generation) == 56,
    "OAC_V5_EVENT_RECORD generation moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD, Sequence) == 64,
    "OAC_V5_EVENT_RECORD provenance moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD, Timestamp100ns) == 72,
    "OAC_V5_EVENT_RECORD timestamp moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD, ScanId) == 80,
    "OAC_V5_EVENT_RECORD scan ID moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD,
    IngestionTimestamp100ns) == 88,
    "OAC_V5_EVENT_RECORD ingestion timestamp moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD, ServiceSequence) == 96,
    "OAC_V5_EVENT_RECORD service sequence moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD, OccurrenceCount) == 104,
    "OAC_V5_EVENT_RECORD occurrence count moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD,
    FirstOccurrence100ns) == 112,
    "OAC_V5_EVENT_RECORD first occurrence moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD,
    LastOccurrence100ns) == 120,
    "OAC_V5_EVENT_RECORD last occurrence moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD, ProcessId) == 128,
    "OAC_V5_EVENT_RECORD process ID moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD, ThreadId) == 136,
    "OAC_V5_EVENT_RECORD thread ID moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD, Address) == 144,
    "OAC_V5_EVENT_RECORD address moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD, Auxiliary) == 152,
    "OAC_V5_EVENT_RECORD auxiliary value moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD, EvidenceFlags) == 160,
    "OAC_V5_EVENT_RECORD evidence flags moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD, PayloadLength) == 168,
    "OAC_V5_EVENT_RECORD payload length moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD, Flags) == 172,
    "OAC_V5_EVENT_RECORD flags moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_V5_EVENT_RECORD, Text) == 176,
    "OAC_V5_EVENT_RECORD payload moved");
OAC_V5_STATIC_ASSERT(sizeof(OAC_V5_EVENT_RECORD) == 560,
    "OAC_V5_EVENT_RECORD layout changed");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_EVIDENCE_READ_RESPONSE,
    Header) == 0, "evidence response header moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_EVIDENCE_READ_RESPONSE,
    Channel) == 56, "evidence response channel moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_EVIDENCE_READ_RESPONSE,
    RecordCount) == 60, "evidence response record count moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_EVIDENCE_READ_RESPONSE,
    PublishedSequence) == 64, "evidence publication cursor moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_EVIDENCE_READ_RESPONSE,
    FirstAvailableSequence) == 72,
    "evidence first available sequence moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_EVIDENCE_READ_RESPONSE,
    LastAvailableSequence) == 80,
    "evidence last available sequence moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_EVIDENCE_READ_RESPONSE,
    AcknowledgedSequence) == 88, "evidence response acknowledgement moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_EVIDENCE_READ_RESPONSE,
    DroppedCount) == 96, "evidence drop count moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_EVIDENCE_READ_RESPONSE,
    FirstLostSequence) == 104, "evidence loss provenance moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_EVIDENCE_READ_RESPONSE,
    LostHighCount) == 112, "evidence high-loss count moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_EVIDENCE_READ_RESPONSE,
    LostCriticalCount) == 120,
    "evidence critical-loss count moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_EVIDENCE_READ_RESPONSE,
    LossLatched) == 128, "evidence loss latch moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_EVIDENCE_READ_RESPONSE,
    Reserved) == 132, "evidence response reserved field moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_EVIDENCE_READ_RESPONSE,
    Records) == 136, "evidence response prefix changed");
OAC_V5_STATIC_ASSERT(sizeof(OAC_SNAPSHOT_RECORD) == 560,
    "OAC_SNAPSHOT_RECORD layout changed");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RECORD,
    Version) == 0, "snapshot record version moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RECORD,
    Size) == 4, "snapshot record size moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RECORD,
    RecordType) == 8, "snapshot record type moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RECORD,
    Flags) == 12, "snapshot record flags moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RECORD,
    Index) == 16, "snapshot record identity moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RECORD,
    Address) == 24, "snapshot record address moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RECORD,
    Length) == 32, "snapshot record length moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RECORD,
    NameLength) == 40, "snapshot record name length moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RECORD,
    Reserved) == 44, "snapshot record reserved field moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RECORD,
    Name) == 48, "snapshot record name moved");
OAC_V5_STATIC_ASSERT(sizeof(OAC_SNAPSHOT_REQUEST) == 96,
    "OAC_SNAPSHOT_REQUEST layout changed");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_REQUEST,
    Header) == 0, "snapshot request header moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_REQUEST,
    Operation) == 48, "snapshot request operation moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_REQUEST,
    SnapshotType) == 52, "snapshot request type moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_REQUEST,
    SnapshotId) == 56, "snapshot request ID moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_REQUEST,
    CursorGeneration) == 72, "snapshot cursor generation moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_REQUEST,
    Cursor) == 80, "snapshot request cursor moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_REQUEST,
    MaximumRecords) == 88, "snapshot page bound moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_REQUEST,
    Reserved) == 92, "snapshot request reserved field moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RESPONSE,
    Header) == 0, "snapshot response header moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RESPONSE,
    SnapshotId) == 56, "snapshot response ID moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RESPONSE,
    ScanId) == 72, "snapshot response scan ID moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RESPONSE,
    CreatedTimestamp100ns) == 80,
    "snapshot creation timestamp moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RESPONSE,
    ExpirationInterruptTime100ns) == 88,
    "snapshot expiration moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RESPONSE,
    CursorGeneration) == 96, "snapshot response generation moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RESPONSE,
    Cursor) == 104, "snapshot response cursor moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RESPONSE,
    NextCursor) == 112, "snapshot response next cursor moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RESPONSE,
    SnapshotType) == 120, "snapshot response type moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RESPONSE,
    State) == 124, "snapshot state moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RESPONSE,
    TotalItems) == 128, "snapshot total count moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RESPONSE,
    AvailableItems) == 132, "snapshot available count moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RESPONSE,
    RecordCount) == 136, "snapshot response record count moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RESPONSE,
    Truncated) == 140, "snapshot truncation flag moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RESPONSE,
    FailureStatus) == 144, "snapshot failure status moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RESPONSE,
    Reserved) == 148, "snapshot response reserved field moved");
OAC_V5_STATIC_ASSERT(FIELD_OFFSET(OAC_SNAPSHOT_RESPONSE,
    Records) == 152, "snapshot response prefix changed");

#undef OAC_V5_STATIC_ASSERT
