#pragma once

#define OAC_RELEASE_VERSION_MAJOR 3
#define OAC_RELEASE_VERSION_MINOR 0
#define OAC_RELEASE_VERSION_PATCH 0
#define OAC_RELEASE_VERSION_BUILD 0

#define OAC_RELEASE_VERSION_TUPLE \
    OAC_RELEASE_VERSION_MAJOR, OAC_RELEASE_VERSION_MINOR, \
    OAC_RELEASE_VERSION_PATCH, OAC_RELEASE_VERSION_BUILD
#define OAC_RELEASE_VERSION_STRING "3.0.0.0"
