[CmdletBinding()]
param(
    [string]$SourceUri =
        'https://download.microsoft.com/download/75bf7aa6-7700-43cc-bbac-9dfc0cc4ed50/VulnerableDriverBlockList.zip',

    [string]$SourceArchivePath,

    [Parameter(Mandatory)]
    [ValidatePattern('^[0-9A-Fa-f]{64}$')]
    [string]$ExpectedZipSha256,

    [string]$OutputPath = (Join-Path $PSScriptRoot '..\OAC-Client\driver_hash_policy.inc')
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$temporary = Join-Path ([IO.Path]::GetTempPath()) (
    'OAC-DriverPolicy-' + [Guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $temporary | Out-Null

try {
    $archive = Join-Path $temporary 'VulnerableDriverBlockList.zip'
    if ($SourceArchivePath) {
        if ($PSBoundParameters.ContainsKey('SourceUri')) {
            throw 'Specify either SourceArchivePath or SourceUri, not both.'
        }
        $sourceArchive = [IO.Path]::GetFullPath($SourceArchivePath)
        if (-not (Test-Path -LiteralPath $sourceArchive -PathType Leaf)) {
            throw "Driver-policy source archive does not exist: $sourceArchive"
        }
        Copy-Item -LiteralPath $sourceArchive -Destination $archive
    } else {
        Invoke-WebRequest -UseBasicParsing -Uri $SourceUri -OutFile $archive
    }
    $actualArchiveHash = (Get-FileHash -LiteralPath $archive -Algorithm SHA256).Hash
    if ($actualArchiveHash -ne $ExpectedZipSha256.ToUpperInvariant()) {
        throw "Driver-policy archive hash mismatch. Expected $ExpectedZipSha256; got $actualArchiveHash"
    }

    $expanded = Join-Path $temporary 'expanded'
    Expand-Archive -LiteralPath $archive -DestinationPath $expanded
    $policyFiles = @(Get-ChildItem -LiteralPath $expanded -Recurse -File |
        Where-Object Name -EQ 'DriverPolicy_Enforced.xml')
    if ($policyFiles.Count -ne 1) {
        throw "Expected one DriverPolicy_Enforced.xml; found $($policyFiles.Count)"
    }

    [xml]$policy = Get-Content -LiteralPath $policyFiles[0].FullName -Raw
    $namespaces = [Xml.XmlNamespaceManager]::new($policy.NameTable)
    $namespaces.AddNamespace('s', 'urn:schemas-microsoft-com:sipolicy')
    $hashes = @($policy.SelectNodes('//s:FileRules/s:Deny[@Hash]', $namespaces) |
        Where-Object {
            $_.Hash -match '^[0-9A-Fa-f]{64}$' -and
            $_.FriendlyName -notmatch '(?i)\bPage\b'
        } |
        ForEach-Object { $_.Hash.ToUpperInvariant() } |
        Sort-Object -Unique)
    if ($hashes.Count -lt 100) {
        throw "The policy yielded only $($hashes.Count) full SHA-256 rules"
    }

    $policyId = [string]$policy.SiPolicy.PolicyID
    $version = [string]$policy.SiPolicy.VersionEx
    if ($policyId -notmatch '^\{[0-9A-Fa-f-]{36}\}$' -or -not $version) {
        throw 'The policy ID or version is missing or malformed.'
    }

    $lines = [Collections.Generic.List[string]]::new()
    $lines.Add('// Generated by tools/Update-OACDriverPolicy.ps1; do not hand edit.')
    $lines.Add("inline constexpr char kOacDriverPolicyId[] = `"$policyId`";")
    $lines.Add("inline constexpr char kOacDriverPolicyVersion[] = `"$version`";")
    $lines.Add("inline constexpr char kOacDriverPolicyArchiveSha256[] = `"$actualArchiveHash`";")
    $lines.Add("inline constexpr std::array<std::string_view, $($hashes.Count)> kOacDeniedDriverAuthenticodeSha256 = {")
    foreach ($hash in $hashes) {
        $lines.Add("    `"$hash`",")
    }
    $lines.Add('};')
    $lines.Add('static_assert(std::ranges::is_sorted(kOacDeniedDriverAuthenticodeSha256));')

    $resolvedOutput = [IO.Path]::GetFullPath($OutputPath)
    $parent = Split-Path -Parent $resolvedOutput
    New-Item -ItemType Directory -Path $parent -Force | Out-Null
    $utf8NoBom = [Text.UTF8Encoding]::new($false)
    [IO.File]::WriteAllText($resolvedOutput, ($lines -join "`n") + "`n", $utf8NoBom)
    Write-Host "Wrote $($hashes.Count) exact driver hashes from policy $version to $resolvedOutput"
}
finally {
    if (Test-Path -LiteralPath $temporary) {
        Remove-Item -LiteralPath $temporary -Recurse -Force
    }
}
